_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  RESNETS:
    DEPTH: 50
    #/home/dell/zhanglimin/code/panoptic_seg/detectron2/detectron2/modeling/backbone/resnet.py
    #50: [3, 4, 6, 3],
    #50: [2, 2, 3, 2],
  META_ARCHITECTURE: "PanopticFPN"
  MASK_ON: True
  ROI_HEADS:
    NUM_CLASSES: 1   # Number of foreground classes
  ROI_BOX_HEAD:
    BBOX_REG_LOSS_TYPE: "giou" #"smooth_l1"
  SEM_SEG_HEAD:
    NUM_CLASSES: 2  # Number of classes in the semantic segmentation head
    LOSS_WEIGHT: 0.5
    #COMMON_STRIDE: 2 #2 # 4
# INPUT:
#   MIN_SIZE_TRAIN: (128,256,) #(128,) #(256,) #(96,)
#   MAX_SIZE_TRAIN: 1333
#   MIN_SIZE_TEST: 128 #256 #96 
#   MAX_SIZE_TEST: 1333
DATASETS:
  TRAIN: ("custom_text_train_separated",)
  TEST: ("custom_text_val_separated",)
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: False
  NUM_WORKERS: 6
SOLVER:
  IMS_PER_BATCH: 7 #5 #4 #16
  #BASE_LR: 0.005 # res50
  BASE_LR: 0.004 # res50_half
  #BASE_LR: 0.0025 # res18
  STEPS: (60000, 80000)
  MAX_ITER: 100000
  LR_SCHEDULER_NAME: WarmupCosineLR #"WarmupMultiStepLR"
OUTPUT_DIR: "/media/dell/6e8a7942-5a27-4e56-bffe-1af5a12aabb4/data/train_results/panoptic_seg/detectron2/text_res50_changed_min128&256_max_1333_20201207"
